# Generated by Django 4.2.1 on 2023-05-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='Электроння почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('image', models.ImageField(upload_to='profile_image/', verbose_name='Фотография профиля')),
                ('status', models.CharField(choices=[('Teacher', 'Ментор'), ('Student', 'Студент'), ('Worker', 'Работник'), ('Unknown', 'Не указано')], default='Unknown', max_length=20, verbose_name='Статус')),
                ('gender', models.CharField(choices=[('Female', 'Женский'), ('Male', 'Мужской'), ('Other', 'Другой'), ('Unknown', 'Не указано')], default='Unknown', max_length=50, verbose_name='Пол')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистраций')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
