# Generated by Django 4.2.1 on 2023-05-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской'), ('Другой', 'Другой'), ('Не указано', 'Не указано')], default='Не указано', max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Ментор', 'Ментор'), ('Студент', 'Студент'), ('Работник', 'Работник'), ('Не указано', 'Не указано')], default='Не указано', max_length=20, verbose_name='Статус'),
        ),
    ]
